### ISSUE TITLE
crashing after GPSD configuration activated

### ISSUE THREAD

**Issue by wanthalf** [farom57/IPARCOS#23]
After having tried to open the GPSD configuration page, the application crashes. Reinstallation does not help. Now always crashes just when trying to open thegeneric control panel by the gear icon, so that nothing can be set at all. Tried both 1.1.0-pre a 1.0.2. Android 9 on LG V30.

**Comment by farom57** [comment]
The project has been moved to https://github.com/INDIForJava/IPARCOS
You can try v2.0 that has just been released.
